version: 2
updates:
  - package-ecosystem: nuget
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - meysamhadeli
    assignees:
      - meysamhadeli
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message
    commit-message:
      prefix: "build"
      include: "scope"
    labels:
      - "dependabot"
      - "dependencies"
    # By default, Dependabot checks for manifest files on the default branch and raises pull requests for version updates against this branch. Use target-branch to specify a different branch
    target-branch: "develop"
