image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start containers
    command: docker-compose -f "./deployments/docker-compose/infrastracture.yaml" up -d --build
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Run
    command: dotnet run

vscode:
  extensions:
    - muhammad-sammy.csharp
