# https://github.com/gitpod-samples/template-dotnet-core-cli-csharp
# https://www.gitpod.io/docs/introduction/languages/dotnet
# https://github.com/gitpod-samples/template-docker-compose
# https://www.gitpod.io/docs/references/gitpod-yml
# https://www.gitpod.io/docs/configure
# https://www.gitpod.io/docs/configure/workspaces/ports

image:
  file: .gitpod.Dockerfile

# https://www.gitpod.io/docs/configure/workspaces/tasks#execution-order
# https://www.gitpod.io/docs/configure/projects/prebuilds
tasks:
  - name: Setup kubectl
    command: bash $GITPOD_REPO_ROOT/scripts/self_signed_certificate_gitpod.sh
  - name: Init Docker-Compose
    init: |
      docker-compose pull
      docker-compose  -f ./deployments/docker-compose/infrastracture.yaml up -d
  - name: Restore & Build
    init: |
      dotnet restore
      dotnet build

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - muhammad-sammy.csharp
