name: build-publish-docker

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:

  build-and-push-docker-image:
    name: Build and Publish Docker image to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      ## With the above semantic-release configuration, will create a release and push the dist/index.js file as well as all the tags required
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        run: |
          docker build -t meysamh66/booking-microservices-flight:latest -f "${{ github.workspace }}/src/Services/Flight/Dockerfile" .
          docker build -t meysamh66/booking-microservices-identity:latest -f "${{ github.workspace }}/src/Services/Identity/Dockerfile" .
          docker build -t meysamh66/booking-microservices-passenger:latest -f "${{ github.workspace }}/src/Services/Passenger/Dockerfile" .
          docker build -t meysamh66/booking-microservices-booking:latest -f "${{ github.workspace }}/src/Services/Booking/Dockerfile" .

      - name: Publish image
        run: |
          docker push meysamh66/booking-microservices-flight:latest
          docker push meysamh66/booking-microservices-identity:latest
          docker push meysamh66/booking-microservices-passenger:latest
          docker push meysamh66/booking-microservices-booking:latest

