name: build-publish-docker

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:

  build-and-push-docker-image:
    name: Build and Publish Docker image to DockerHub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: |
            ./src/Services/Flight/Dockerfile
            ./src/Services/Identity/Dockerfile
            ./src/Services/Passenger/Dockerfile
            ./src/Services/Booking/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/booking-microservices-flight:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/booking-microservices-identity:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/booking-microservices-passenger:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/booking-microservices-booking:latest

