name: build-publish-docker

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:

  build-and-push-docker-image:
    name: Build and Publish Docker image to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Tag
        id: vars
        run: echo ::set-output name=tag::${git describe --abbrev=0}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        run: |
          docker build -t meysamh66/booking-microservices-flight:${{ steps.vars.outputs.tag }} -f "${{ github.workspace }}/src/Services/Flight/Dockerfile" .
          docker build -t meysamh66/booking-microservices-identity:${{ steps.vars.outputs.tag }} -f "${{ github.workspace }}/src/Services/Identity/Dockerfile" .
          docker build -t meysamh66/booking-microservices-passenger:${{ steps.vars.outputs.tag }} -f "${{ github.workspace }}/src/Services/Passenger/Dockerfile" .
          docker build -t meysamh66/booking-microservices-booking:${{ steps.vars.outputs.tag }} -f "${{ github.workspace }}/src/Services/Booking/Dockerfile" .

      - name: Publish image
        run: |
          docker push meysamh66/booking-microservices-flight:${{ steps.vars.outputs.tag }}
          docker push meysamh66/booking-microservices-identity:${{ steps.vars.outputs.tag }}
          docker push meysamh66/booking-microservices-passenger:${{ steps.vars.outputs.tag }}
          docker push meysamh66/booking-microservices-booking:${{ steps.vars.outputs.tag }}

