name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t myimage:${{ github.sha }} -f ./src/Services/Flight/Dockerfile .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push to Docker Hub
        run: docker push myimage:${{ github.sha }}
