name: build-publish-docker

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:

  build-and-push-docker-image:
    name: Build and Publish Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        run: |
          docker build -t meysamh66/booking-microservices-flight:$(echo $GITHUB_REF | sed 's/refs\/tags\///') -f "${{ github.workspace }}/src/Services/Flight/Dockerfile" .
          docker build -t meysamh66/booking-microservices-identity:$(echo $GITHUB_REF | sed 's/refs\/tags\///') -f "${{ github.workspace }}/src/Services/Identity/Dockerfile" .
          docker build -t meysamh66/booking-microservices-passenger:$(echo $GITHUB_REF | sed 's/refs\/tags\///') -f "${{ github.workspace }}/src/Services/Passenger/Dockerfile" .
          docker build -t meysamh66/booking-microservices-booking:$(echo $GITHUB_REF | sed 's/refs\/tags\///') -f "${{ github.workspace }}/src/Services/Booking/Dockerfile" .

      - name: Publish image
        run: |
          docker push meysamh66/booking-microservices-flight:$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          docker push meysamh66/booking-microservices-identity:$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          docker push meysamh66/booking-microservices-passenger:$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          docker push meysamh66/booking-microservices-booking:$(echo $GITHUB_REF | sed 's/refs\/tags\///')

