name: github-packages

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:

  build-and-push-docker-image:
    name: Build and Publish Docker image to Github Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/flight:latest -f "${{ github.workspace }}/src/Services/Flight/Dockerfile" .
          docker build -t ghcr.io/${{ github.repository }}/identity:latest -f "${{ github.workspace }}/src/Services/Identity/Dockerfile" .
          docker build -t ghcr.io/${{ github.repository }}/passenger:latest -f "${{ github.workspace }}/src/Services/Passenger/Dockerfile" .
          docker build -t ghcr.io/${{ github.repository }}/booking:latest -f "${{ github.workspace }}/src/Services/Booking/Dockerfile" .

      - name: Publish image
        run: |
          docker push ghcr.io/${{ github.repository }}/flight:latest
          docker push ghcr.io/${{ github.repository }}/identity:latest
          docker push ghcr.io/${{ github.repository }}/passenger:latest
          docker push ghcr.io/${{ github.repository }}/booking:latest


